name = "multiplayer-finaller"
main = "worker.js"
compatibility_date = "2026-08-16"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "AUTH", class_name = "Auth" }
]

[exports.Room]
type = "durable-object"
storage = "sqlite"

[exports.Auth]
type = "durable-object"
storage = "sqlite"
